name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Test Build
        run: npm run build

      - name: check lint
        run: npm run lint

      - name: check exports
        run: npm run check-exports

      - name: check format
        run: npm run check-format

      - name: Test
        run: npm test
        env:
          OSU_API_KEY: 1235555
